import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    svgCurve: {
        position: 'absolute',
        width: '110%'
    },
    headerContainer: {
        alignItems: 'flex-start',
        paddingLeft: 18,
        paddingTop: 10,
    },
    headerText1: {
        fontFamily: 'Poppins-SemiBold',
        fontSize: 22,
        marginTop: 10,
        fontWeight: 'bold',
        color: 'white',
        paddingTop: 10,
    },
    headerText2: {
        fontFamily: 'Poppins-Black',
        marginTop: 46,
        paddingLeft: 18,
        position: 'absolute',
        fontSize: 50,
        marginBottom: 50,
        color: '#A2D2FF',
    },
    hd2: {
        fontFamily: 'Poppins-Black',
        fontSize: 23,
        marginTop: 130,
        marginBottom: 25,
        textAlign: 'center',
        color: 'black',
    },
    container1: {
        flex: 1,
        backgroundColor: '#F8F7FF',
        backgroundColor: '#B8B8FF',
    },
    categoryItem: {
        paddingHorizontal: 20,
        height: 70,
        width: '90%',
        marginLeft: 20,
        backgroundColor: 'white',
        justifyContent: 'center',
        borderRadius: 22,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    categoryText: {
        fontFamily: 'Poppins-Extrabold',
        fontSize: 25,
        color: '#B8B8FF',
    },
    deleteButton: {
        width: 30,
        height: 70,
        paddingTop: 18,
        marginRight: 15,
    },
    addButton1: {
        borderRadius: 50,
        width: 80,
        height: 80,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        bottom: 32,
        right: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 4,
        elevation: 4,
    },
    flatListContent: {
        paddingBottom: 80,
    },
    headerContainer2: {
        alignItems: 'flex-start',
    },
    headerText22: {
        fontFamily: 'Poppins-ExtraBold',
        fontSize: 22,
        paddingTop: 20,
        paddingLeft: 25,
        color: 'black',
    },
    container2: {
        flex: 1,
        backgroundColor: '#B8B8FF',
    },
    taskItem: {
        backgroundColor: 'white',
        width: '90%',
        marginTop: 10,
        flexDirection: 'row',
        marginHorizontal: 20,
        borderRadius: 22,
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4, 
    },
    taskDetails: {
        flex: 1,
    },
    taskText: {
        fontFamily: 'Poppins-Bold',
        color: '#9381FF',
        fontSize: 18,
    },
    taskDescription: {
        fontFamily: 'Poppins-SemiBold',
        fontSize: 14,
        color: '#666',
    },
    taskActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addButton2: {
        position: 'absolute',
        bottom: 35,
        width: '85%',
        backgroundColor: '#9381FF',
        borderRadius: 50, 
        alignSelf: 'center', 
        paddingTop: 20,
        padding: 15, 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4, 
        height: 70,
    },
    addButtonContainer: {
        flexDirection: 'row', 
        justifyContent: 'center', 
        alignItems: 'center', 
    },
    addButtonText: {
        fontSize: 24,
        fontFamily: 'Poppins-Bold',
        color: 'white',
        fontWeight: 'bold', 
        marginRight: 5,
    },
    addButtonIcon: {
        marginLeft: 5,
    },

    //Edit Task Modal
    editTaskModal: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    editTaskContainer: {
        backgroundColor: '#B8B8FF',
        padding: 20,
        borderRadius: 25,
        width: '80%',
        alignItems: 'center',
    },
    editTaskTitle: {
        fontSize: 26,
        fontFamily: 'Poppins-Bold',
        backgroundColor: '#fdc5f5',
        color: 'black',
        paddingTop: 10,
        marginBottom: 15,
        marginTop: 5,
        borderRadius: 25,
        textAlign: 'center',
        width: 260,
        height: 55,
        overflow: 'hidden',
    },
    editTaskInput: {
        height: 50,
        width: '88%',
        borderRadius: 15,
        marginBottom: 8,
        paddingHorizontal: 12,
        backgroundColor: '#F8F7FF',
    },
    saveButton: {
        backgroundColor: '#fdc5f5',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        width: 80,
        height: 50,
    },
    //Add Task Modal
    addTaskModal: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    addTaskContainer: {
        backgroundColor: '#B8B8FF',
        padding: 20,
        borderRadius: 25,
        width: '80%',
        alignItems: 'center',
    },
    addTaskTitle: {
        fontSize: 26,
        fontFamily: 'Poppins-Bold',
        backgroundColor: '#fdc5f5',
        color: 'black',
        paddingTop: 10,
        marginBottom: 15,
        marginTop: 5,
        borderRadius: 25,
        textAlign: 'center',
        width: 260,
        height: 55,
        overflow: 'hidden',
    },
    addTaskInput: {
        height: 50,
        width: '88%',
        borderRadius: 15,
        marginBottom: 8,
        paddingHorizontal: 12,
        backgroundColor: '#F8F7FF',
    },
    saveButton: {
        backgroundColor: '#fdc5f5',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        width: 80,
        height: 50,
    },
});

export default styles;
